version: '3.4'
services:
  postgres:
    image: postgres
    user: "root"
    environment:
      POSTGRES_DB: switchit_simple_cqrs_model
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    networks:
    - switchit
    volumes:
    - "pgdata:/var/lib/postgresql"

  app:
    image: switchit-conseil/simple-cqrs-model:latest
    working_dir: /home/app
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_DATABASE: switchit_simple_cqrs_model
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_SYNCHRONIZE: "true"
    ports:
    - "3000:3000"
    networks:
    - switchit
volumes:
  pgdata:

networks:
  switchit:
    driver: overlay
    driver_opts:
      encrypted: "true"
